# Generated by Django 5.0.6 on 2024-06-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_author_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
